# Generated by Django 5.1.7 on 2025-04-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kuebelwaschen_him2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KuebelArt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="kuebeleintrag",
            name="kuebel_art",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="kuebelwaschen_him2.kuebelart",
            ),
        ),
    ]
