# Generated by Django 5.1.7 on 2025-05-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kuebelwaschen_him2", "0008_rename_name_kuebelart_kuebel_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kuebelart",
            options={
                "ordering": ["id"],
                "verbose_name": "Kübelwaschen Behältertyp",
                "verbose_name_plural": "Kübelwaschen Behältertypen",
            },
        ),
    ]
