# Generated by Django 5.1.7 on 2025-05-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_kuebelwaschplatz", "0001_initial"),
        ("him2_referenzdaten", "0003_alter_schicht_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kuebelsession",
            name="user_name_manuell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="him2_referenzdaten.mitarbeiter",
                verbose_name="Mitarbeiter",
            ),
        ),
    ]
