# Generated by Django 5.1.7 on 2025-05-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("him2_kuebelwaschplatz", "0002_alter_kuebelsession_user_name_manuell"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kuebelsession",
            old_name="user_name_manuell",
            new_name="mitarbeiter",
        ),
    ]
