# Generated by Django 5.1.7 on 2025-05-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "him2_kuebelwaschplatz",
            "0003_rename_user_name_manuell_kuebelsession_mitarbeiter",
        ),
        ("him2_referenzdaten", "0006_alter_betankung_amount_fuel"),
    ]

    operations = [
        migrations.AddField(
            model_name="kuebelsession",
            name="tank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="him2_referenzdaten.betankung",
            ),
        ),
    ]
