# Generated by Django 5.1.7 on 2025-05-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_kuebelwaschplatz", "0004_kuebelsession_tank"),
        ("him2_referenzdaten", "0015_remove_betankung_created_at_tank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kuebelsession",
            name="tank",
        ),
        migrations.AddField(
            model_name="kuebelsession",
            name="tank_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kuebel_sessions",
                to="him2_referenzdaten.betankungsession",
            ),
        ),
    ]
