# Generated by Django 5.1.7 on 2025-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kuebelwaschen_him2",
            "0005_alter_kuebelart_options_alter_kuebeleintrag_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kuebeleintrag",
            name="reinigung_h",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="kuebeleintrag",
            name="sonstiges_h",
            field=models.FloatField(default=0),
        ),
    ]
