# Generated by Django 5.1.7 on 2025-05-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kuebelwaschen_him2", "0009_alter_kuebelart_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kuebelart",
            options={
                "ordering": ["id"],
                "verbose_name": "Referenzdaten: Behältertyp",
                "verbose_name_plural": "Referenzdaten: Behältertypen",
            },
        ),
    ]
