# Generated by Django 5.1.7 on 2025-05-07 14:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbhProdTyp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bez_abh_prod", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Abholung_Produktion",
                "verbose_name_plural": "Abholung_Produktion",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PresseBallenTyp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ball_name", models.CharField(max_length=100, unique=True)),
                (
                    "ball_gewicht",
                    models.FloatField(
                        default=0.5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Ballentyp",
                "verbose_name_plural": "Ballentypen",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Schicht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schichten", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Schicht",
                "verbose_name_plural": "Schichten",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ZeitAktivitaetTyp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zeit_typ", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "verbose_name": "Zeit_Typ",
                "verbose_name_plural": "Zeit_Typen",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Produktion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("anzahl", models.FloatField(default=0)),
                (
                    "abh_prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pressenlinie.abhprodtyp",
                    ),
                ),
                (
                    "ballentyp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pressenlinie.presseballentyp",
                    ),
                ),
                (
                    "schicht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pressenlinie.schicht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schicht-Zeiten",
                "verbose_name_plural": "Schicht-Zeiten",
            },
        ),
        migrations.CreateModel(
            name="Aktivitaet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("stromzaehler", models.IntegerField(default=0)),
                ("ballenpresse_zaehler", models.IntegerField(default=0)),
                (
                    "schicht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pressenlinie.schicht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schicht-Zeiten",
                "verbose_name_plural": "Schicht-Zeiten",
            },
        ),
        migrations.CreateModel(
            name="Stundeneingabe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("dauer", models.FloatField(default=0)),
                (
                    "schicht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pressenlinie.schicht",
                    ),
                ),
                (
                    "zeittyp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pressenlinie.zeitaktivitaettyp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schicht-Zeiten",
                "verbose_name_plural": "Schicht-Zeiten",
            },
        ),
    ]
