# Generated by Django 5.1.7 on 2025-05-13 11:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_pressenlinie", "0001_initial"),
        ("him2_referenzdaten", "0009_betankung_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="produktion",
            name="mitarbeiter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Produktionsmitarbeiter",
                to="him2_referenzdaten.mitarbeiter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produktion",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stundeneingabe",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Kommentar"),
        ),
        migrations.AddField(
            model_name="stundeneingabe",
            name="created_date_mitarbeiter",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stundeneingabe",
            name="schicht_mitarbeiter_1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Schicht_Mitarbeiter_1",
                to="him2_referenzdaten.mitarbeiter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stundeneingabe",
            name="schicht_mitarbeiter_2",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Schicht_Mitarbeiter_2",
                to="him2_referenzdaten.mitarbeiter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stundeneingabe",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
