# Generated by Django 5.1.7 on 2025-05-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pressenlinie", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abhprodtyp",
            options={
                "ordering": ["id"],
                "verbose_name": "Referenzdaten: Abholung_Produktion",
                "verbose_name_plural": "Referenzdaten: Abholung_Produktion",
            },
        ),
        migrations.AlterModelOptions(
            name="aktivitaet",
            options={
                "verbose_name": "Erfassung Aktivitäten",
                "verbose_name_plural": "Erfassung Aktivitäten",
            },
        ),
        migrations.AlterModelOptions(
            name="presseballentyp",
            options={
                "ordering": ["id"],
                "verbose_name": "Referenzdaten: Ballentyp",
                "verbose_name_plural": "Referenzdaten: Ballentypen",
            },
        ),
        migrations.AlterModelOptions(
            name="produktion",
            options={
                "verbose_name": "Erfassung Ballenproduktion u. -abholung",
                "verbose_name_plural": "Erfassung Ballenproduktion u. -abholung",
            },
        ),
        migrations.AlterModelOptions(
            name="schicht",
            options={
                "ordering": ["id"],
                "verbose_name": "Referenzdaten: Schicht",
                "verbose_name_plural": "Referenzdaten: Schicht",
            },
        ),
        migrations.AlterModelOptions(
            name="stundeneingabe",
            options={
                "verbose_name": "Erfassung Stunden",
                "verbose_name_plural": "Erfassung Stunden",
            },
        ),
        migrations.AlterModelOptions(
            name="zeitaktivitaettyp",
            options={
                "ordering": ["id"],
                "verbose_name": "Referenzdaten: Zeit_Typ",
                "verbose_name_plural": "Referenzdaten: Zeit_Typen",
            },
        ),
    ]
