# Generated by Django 5.1.7 on 2025-05-13 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_pressenlinie", "0002_produktion_mitarbeiter_produktion_user_and_more"),
        ("him2_referenzdaten", "0010_rename_fzg_name_fahrzeug_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StundenEingabeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_date_mitarbeiter", models.DateField()),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Kommentar"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Erfassung Stunden",
                "verbose_name_plural": "Erfassung Stunden",
            },
        ),
        migrations.CreateModel(
            name="StundenEingabeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dauer", models.FloatField(default=0)),
                (
                    "schicht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="him2_referenzdaten.schicht",
                    ),
                ),
                (
                    "schicht_mitarbeiter_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Schicht_Mitarbeiter_1",
                        to="him2_referenzdaten.mitarbeiter",
                    ),
                ),
                (
                    "schicht_mitarbeiter_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Schicht_Mitarbeiter_2",
                        to="him2_referenzdaten.mitarbeiter",
                    ),
                ),
                (
                    "zeittyp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="him2_pressenlinie.zeitaktivitaettyp",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="him2_pressenlinie.stundeneingabesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erfassung Stunde Detail",
                "verbose_name_plural": "Erfassung Stunden Details",
            },
        ),
        migrations.DeleteModel(
            name="Stundeneingabe",
        ),
    ]
