# Generated by Django 5.1.7 on 2025-05-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "him2_pressenlinie",
            "0003_stundeneingabesession_stundeneingabedetails_and_more",
        ),
        ("him2_referenzdaten", "0010_rename_fzg_name_fahrzeug_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stundeneingabedetails",
            name="schicht_mitarbeiter_1",
        ),
        migrations.RemoveField(
            model_name="stundeneingabedetails",
            name="schicht_mitarbeiter_2",
        ),
        migrations.AlterField(
            model_name="stundeneingabedetails",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="him2_pressenlinie.stundeneingabesession",
            ),
        ),
        migrations.CreateModel(
            name="SchichtEingabeMitarbeiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mitarbeiter_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="him2_referenzdaten.mitarbeiter",
                    ),
                ),
                (
                    "mitarbeiter_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="him2_referenzdaten.mitarbeiter",
                    ),
                ),
                (
                    "schicht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="him2_referenzdaten.schicht",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="him2_pressenlinie.stundeneingabesession",
                    ),
                ),
            ],
        ),
    ]
