# Generated by Django 5.1.7 on 2025-05-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "him2_pressenlinie",
            "0004_remove_stundeneingabedetails_schicht_mitarbeiter_1_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="abhprodtyp",
            old_name="bez_abh_prod",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="zeitaktivitaettyp",
            old_name="zeit_typ",
            new_name="name",
        ),
    ]
