# Generated by Django 5.1.7 on 2025-05-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_pressenlinie", "0005_rename_bez_abh_prod_abhprodtyp_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stundeneingabesession",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
