# Generated by Django 5.1.7 on 2025-05-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_pressenlinie", "0006_alter_stundeneingabesession_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="aktivitaet",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="him2_pressenlinie.stundeneingabesession",
            ),
            preserve_default=False,
        ),
    ]
