# Generated by Django 5.1.7 on 2025-05-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_pressenlinie", "0007_aktivitaet_session"),
        ("him2_referenzdaten", "0016_rename_session_betankung_tank_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="stundeneingabesession",
            name="tank_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="presse_stunden",
                to="him2_referenzdaten.betankungsession",
            ),
        ),
    ]
