# Generated by Django 5.1.7 on 2025-05-09 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KuebelArt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kuebel_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Referenzdaten: Behältertyp",
                "verbose_name_plural": "Referenzdaten: Behältertypen",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PresseBallenTyp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ball_name", models.CharField(max_length=100, unique=True)),
                (
                    "ball_gewicht",
                    models.FloatField(
                        default=0.5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Referenzdaten: Ballentyp",
                "verbose_name_plural": "Referenzdaten: Ballentypen",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Schicht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schichten", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Referenzdaten: Schicht",
                "verbose_name_plural": "Referenzdaten: Schicht",
                "ordering": ["id"],
            },
        ),
    ]
