# Generated by Django 5.1.7 on 2025-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fahrzeug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fzg_name", models.CharField(max_length=30, unique=True)),
                ("bereich", models.CharField(max_length=30)),
                ("kostenstelle", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "verbose_name": "Referenzdaten: Fahrzeug HIM2",
                "verbose_name_plural": "Referenzdaten: Fahrzeuge HIM2",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Mitarbeiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("funktion", models.CharField(max_length=40)),
                ("intern_extern", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Referenzdaten: Mitarbeiter HIM2",
                "verbose_name_plural": "Referenzdaten: Mitarbeiter HIM2",
                "ordering": ["id"],
            },
        ),
    ]
