# Generated by Django 5.1.7 on 2025-05-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0002_fahrzeug_mitarbeiter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schicht",
            options={
                "ordering": ["id"],
                "verbose_name": "Referenzdaten: Schicht",
                "verbose_name_plural": "Referenzdaten: Schichten",
            },
        ),
    ]
