# Generated by Django 5.1.7 on 2025-05-09 12:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0003_alter_schicht_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Betankung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daten_eingabe_von", models.CharField(max_length=40)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "amount_fuel",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fahrzeug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="him2_referenzdaten.mitarbeiter",
                        verbose_name="Fahrzeug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Betankungen HIM2",
                "verbose_name_plural": "Betankungen HIM2",
                "ordering": ["id"],
            },
        ),
    ]
