# Generated by Django 5.1.7 on 2025-05-09 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0004_betankung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betankung",
            name="daten_eingabe_von",
            field=models.CharField(max_length=40, verbose_name="von welcher App:"),
        ),
        migrations.AlterField(
            model_name="betankung",
            name="fahrzeug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="him2_referenzdaten.fahrzeug",
                verbose_name="Fahrzeug",
            ),
        ),
    ]
