# Generated by Django 5.1.7 on 2025-05-09 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0005_alter_betankung_daten_eingabe_von_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betankung",
            name="amount_fuel",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Diesel [l]",
            ),
        ),
    ]
