# Generated by Django 5.1.7 on 2025-05-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0006_alter_betankung_amount_fuel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betankung",
            name="fahrzeug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="him2_referenzdaten.fahrzeug",
                verbose_name="Fahrzeug",
            ),
        ),
    ]
