# Generated by Django 5.1.7 on 2025-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0007_alter_betankung_fahrzeug"),
    ]

    operations = [
        migrations.AddField(
            model_name="betankung",
            name="end_time",
            field=models.TimeField(default="00:00"),
        ),
        migrations.AddField(
            model_name="betankung",
            name="start_time",
            field=models.TimeField(default="00:00"),
        ),
    ]
