# Generated by Django 5.1.7 on 2025-05-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0009_betankung_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fahrzeug",
            old_name="fzg_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="kuebelart",
            old_name="kuebel_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="presseballentyp",
            old_name="ball_gewicht",
            new_name="gewicht",
        ),
        migrations.RenameField(
            model_name="presseballentyp",
            old_name="ball_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="schicht",
            old_name="schichten",
            new_name="name",
        ),
    ]
