# Generated by Django 5.1.7 on 2025-05-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0010_rename_fzg_name_fahrzeug_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="betankung",
            old_name="created_at",
            new_name="created_at_tank",
        ),
    ]
