# Generated by Django 5.1.7 on 2025-05-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0011_rename_created_at_betankung_created_at_tank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betankung",
            name="end_time",
            field=models.TimeField(default="06:00"),
        ),
        migrations.AlterField(
            model_name="betankung",
            name="start_time",
            field=models.TimeField(default="06:00"),
        ),
    ]
