# Generated by Django 5.1.7 on 2025-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "him2_referenzdaten",
            "0012_alter_betankung_end_time_alter_betankung_start_time",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betankung",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="betankung",
            name="start_time",
        ),
        migrations.AddField(
            model_name="betankung",
            name="laufzeit",
            field=models.DurationField(default="00:00"),
        ),
    ]
