# Generated by Django 5.1.7 on 2025-05-15 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0013_remove_betankung_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betankung",
            name="amount_fuel",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Diesel [L]",
            ),
        ),
        migrations.AlterField(
            model_name="betankung",
            name="created_at_tank",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
