# Generated by Django 5.1.7 on 2025-05-16 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0014_alter_betankung_amount_fuel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betankung",
            name="created_at_tank",
        ),
        migrations.RemoveField(
            model_name="betankung",
            name="daten_eingabe_von",
        ),
        migrations.RemoveField(
            model_name="betankung",
            name="user",
        ),
        migrations.CreateModel(
            name="BetankungSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daten_eingabe_von",
                    models.CharField(max_length=40, verbose_name="von welcher App:"),
                ),
                ("created_at_tank", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Betankung Session HIM2",
                "verbose_name_plural": "Betankung Sessions HIM2",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="betankung",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="betankungen",
                to="him2_referenzdaten.betankungsession",
            ),
        ),
    ]
