# Generated by Django 5.1.7 on 2025-05-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("him2_referenzdaten", "0015_remove_betankung_created_at_tank_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="betankung",
            old_name="session",
            new_name="tank_session",
        ),
    ]
