# Generated by Django 5.1.7 on 2025-04-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "him2_kuebelwaschplatz",
            "0003_alter_kuebelart_options_alter_kuebelsession_user",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="kuebelsession",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
