# Generated by Django 5.1.7 on 2025-04-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("him2_kuebelwaschplatz", "0004_alter_kuebelsession_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kuebelart",
            options={
                "ordering": ["id"],
                "verbose_name": "Behältertyp",
                "verbose_name_plural": "Behältertypen",
            },
        ),
        migrations.AlterModelOptions(
            name="kuebeleintrag",
            options={
                "verbose_name": "Kübel-Detaileintrag",
                "verbose_name_plural": "Kübel-Detaileinträge",
            },
        ),
        migrations.AlterModelOptions(
            name="kuebelsession",
            options={
                "verbose_name": "Kübel-Tagesübersicht",
                "verbose_name_plural": "Kübel-Tagesübersichten",
            },
        ),
    ]
