# Generated by Django 5.1.7 on 2025-04-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "him2_kuebelwaschplatz",
            "0006_kuebeleintrag_reinigung_h_kuebeleintrag_sonstiges_h",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="kuebelsession",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Kommentar"),
        ),
        migrations.AlterField(
            model_name="kuebelsession",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Verantwortlicher"),
        ),
    ]
