# Generated by Django 5.1.7 on 2025-04-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kuebelwaschen_him2", "0007_alter_kuebelsession_comments_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kuebelart",
            old_name="name",
            new_name="kuebel_name",
        ),
        migrations.RenameField(
            model_name="kuebelsession",
            old_name="name",
            new_name="mitarbeiter",
        ),
    ]
