# Generated by Django 5.1.7 on 2025-03-31 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_entry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containercount",
            name="alu",
            field=models.IntegerField(
                default=0,
                help_text="Alu Dosen (Kübel - 8,5 kg)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="containercount",
            name="holz",
            field=models.IntegerField(
                default=0,
                help_text="Holz (Container - 6 t)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="containercount",
            name="kanister",
            field=models.IntegerField(
                default=0,
                help_text="Kanister (1 Container = 5 Ballen)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="containercount",
            name="karton",
            field=models.IntegerField(
                default=0,
                help_text="Karton (Container - 6 t)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="containercount",
            name="magnetschrott",
            field=models.IntegerField(
                default=0,
                help_text="Magnetschrott (Container - 6 t)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
