# Generated by Django 5.1.7 on 2025-03-12 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_entry", "0007_rename_container_count_containercount"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocollist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
