# Generated by Django 5.1.7 on 2025-03-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0008_protocollist_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocollist",
            name="protocollist",
            field=models.TextField(default="keine Angabe", help_text="Protokollführer"),
        ),
    ]
