# Generated by Django 5.1.7 on 2025-03-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_entry", "0011_alter_employee_break_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="attribut",
            field=models.CharField(default="", max_length=100),
        ),
    ]
